spring.datasource.url=jdbc:postgresql://localhost:5432/finance_db
spring.datasource.username=postgres

spring.datasource.password=${DB_PASSWORD:yourpassword}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

spring.batch.jdbc.initialize-schema=always