spring.datasource.url=jdbc:postgresql://localhost:5432/finance_db
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.password=Manya565@Ryan

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

spring.batch.jdbc.initialize-schema=always

management.endpoints.web.exposure.include=health,metrics

management.endpoint.health.show-details=always

spring.batch.jdbc.initialize-schema=always